// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: delete_user_urls_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*Urls `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delete_user_urls_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delete_user_urls_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_delete_user_urls_request_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteUserURLsRequest) GetUrls() []*Urls {
	if x != nil {
		return x.Urls
	}
	return nil
}

type Urls struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=urls,proto3" json:"urls,omitempty"`
}

func (x *Urls) Reset() {
	*x = Urls{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delete_user_urls_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Urls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Urls) ProtoMessage() {}

func (x *Urls) ProtoReflect() protoreflect.Message {
	mi := &file_delete_user_urls_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Urls.ProtoReflect.Descriptor instead.
func (*Urls) Descriptor() ([]byte, []int) {
	return file_delete_user_urls_request_proto_rawDescGZIP(), []int{1}
}

func (x *Urls) GetUrls() *wrapperspb.StringValue {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_delete_user_urls_request_proto protoreflect.FileDescriptor

var file_delete_user_urls_request_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x72,
	0x6c, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x32, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52,
	0x4c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x04, 0x75, 0x72, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x22, 0x38, 0x0a, 0x04, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x30, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x42, 0x10,
	0x5a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delete_user_urls_request_proto_rawDescOnce sync.Once
	file_delete_user_urls_request_proto_rawDescData = file_delete_user_urls_request_proto_rawDesc
)

func file_delete_user_urls_request_proto_rawDescGZIP() []byte {
	file_delete_user_urls_request_proto_rawDescOnce.Do(func() {
		file_delete_user_urls_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_delete_user_urls_request_proto_rawDescData)
	})
	return file_delete_user_urls_request_proto_rawDescData
}

var file_delete_user_urls_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delete_user_urls_request_proto_goTypes = []any{
	(*DeleteUserURLsRequest)(nil),  // 0: DeleteUserURLsRequest
	(*Urls)(nil),                   // 1: Urls
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
}
var file_delete_user_urls_request_proto_depIdxs = []int32{
	1, // 0: DeleteUserURLsRequest.urls:type_name -> Urls
	2, // 1: Urls.urls:type_name -> google.protobuf.StringValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_delete_user_urls_request_proto_init() }
func file_delete_user_urls_request_proto_init() {
	if File_delete_user_urls_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delete_user_urls_request_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserURLsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delete_user_urls_request_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Urls); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delete_user_urls_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delete_user_urls_request_proto_goTypes,
		DependencyIndexes: file_delete_user_urls_request_proto_depIdxs,
		MessageInfos:      file_delete_user_urls_request_proto_msgTypes,
	}.Build()
	File_delete_user_urls_request_proto = out.File
	file_delete_user_urls_request_proto_rawDesc = nil
	file_delete_user_urls_request_proto_goTypes = nil
	file_delete_user_urls_request_proto_depIdxs = nil
}
