// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: find_user_urls_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindUserURLsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserUrls []*UserURLs `protobuf:"bytes,1,rep,name=user_urls,json=userUrls,proto3" json:"user_urls,omitempty"`
}

func (x *FindUserURLsResponse) Reset() {
	*x = FindUserURLsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_find_user_urls_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserURLsResponse) ProtoMessage() {}

func (x *FindUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_find_user_urls_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserURLsResponse.ProtoReflect.Descriptor instead.
func (*FindUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_find_user_urls_response_proto_rawDescGZIP(), []int{0}
}

func (x *FindUserURLsResponse) GetUserUrls() []*UserURLs {
	if x != nil {
		return x.UserUrls
	}
	return nil
}

type UserURLs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl    *ShortURL    `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl *OriginalURL `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *UserURLs) Reset() {
	*x = UserURLs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_find_user_urls_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURLs) ProtoMessage() {}

func (x *UserURLs) ProtoReflect() protoreflect.Message {
	mi := &file_find_user_urls_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURLs.ProtoReflect.Descriptor instead.
func (*UserURLs) Descriptor() ([]byte, []int) {
	return file_find_user_urls_response_proto_rawDescGZIP(), []int{1}
}

func (x *UserURLs) GetShortUrl() *ShortURL {
	if x != nil {
		return x.ShortUrl
	}
	return nil
}

func (x *UserURLs) GetOriginalUrl() *OriginalURL {
	if x != nil {
		return x.OriginalUrl
	}
	return nil
}

var File_find_user_urls_response_proto protoreflect.FileDescriptor

var file_find_user_urls_response_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x66, 0x69, 0x6e, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x73,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0b, 0x77, 0x72, 0x61, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x14,
	0x46, 0x69, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x72, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52,
	0x4c, 0x73, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x63, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x26, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x12, 0x2f, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61,
	0x6c, 0x55, 0x52, 0x4c, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72,
	0x6c, 0x42, 0x10, 0x5a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_find_user_urls_response_proto_rawDescOnce sync.Once
	file_find_user_urls_response_proto_rawDescData = file_find_user_urls_response_proto_rawDesc
)

func file_find_user_urls_response_proto_rawDescGZIP() []byte {
	file_find_user_urls_response_proto_rawDescOnce.Do(func() {
		file_find_user_urls_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_find_user_urls_response_proto_rawDescData)
	})
	return file_find_user_urls_response_proto_rawDescData
}

var file_find_user_urls_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_find_user_urls_response_proto_goTypes = []any{
	(*FindUserURLsResponse)(nil), // 0: FindUserURLsResponse
	(*UserURLs)(nil),             // 1: UserURLs
	(*ShortURL)(nil),             // 2: ShortURL
	(*OriginalURL)(nil),          // 3: OriginalURL
}
var file_find_user_urls_response_proto_depIdxs = []int32{
	1, // 0: FindUserURLsResponse.user_urls:type_name -> UserURLs
	2, // 1: UserURLs.short_url:type_name -> ShortURL
	3, // 2: UserURLs.original_url:type_name -> OriginalURL
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_find_user_urls_response_proto_init() }
func file_find_user_urls_response_proto_init() {
	if File_find_user_urls_response_proto != nil {
		return
	}
	file_wraps_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_find_user_urls_response_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FindUserURLsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_find_user_urls_response_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserURLs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_find_user_urls_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_find_user_urls_response_proto_goTypes,
		DependencyIndexes: file_find_user_urls_response_proto_depIdxs,
		MessageInfos:      file_find_user_urls_response_proto_msgTypes,
	}.Build()
	File_find_user_urls_response_proto = out.File
	file_find_user_urls_response_proto_rawDesc = nil
	file_find_user_urls_response_proto_goTypes = nil
	file_find_user_urls_response_proto_depIdxs = nil
}
