// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: handle_create_short_url_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleCreateShortURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Jwt    *JWT    `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
}

func (x *HandleCreateShortURLResponse) Reset() {
	*x = HandleCreateShortURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handle_create_short_url_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleCreateShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleCreateShortURLResponse) ProtoMessage() {}

func (x *HandleCreateShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_handle_create_short_url_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleCreateShortURLResponse.ProtoReflect.Descriptor instead.
func (*HandleCreateShortURLResponse) Descriptor() ([]byte, []int) {
	return file_handle_create_short_url_response_proto_rawDescGZIP(), []int{0}
}

func (x *HandleCreateShortURLResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HandleCreateShortURLResponse) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_handle_create_short_url_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_handle_create_short_url_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_handle_create_short_url_response_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetResult() *wrapperspb.StringValue {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_handle_create_short_url_response_proto protoreflect.FileDescriptor

var file_handle_create_short_url_response_proto_rawDesc = []byte{
	0x0a, 0x26, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x77, 0x72, 0x61, 0x70, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x1c, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x22, 0x3e,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x10,
	0x5a, 0x0e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_handle_create_short_url_response_proto_rawDescOnce sync.Once
	file_handle_create_short_url_response_proto_rawDescData = file_handle_create_short_url_response_proto_rawDesc
)

func file_handle_create_short_url_response_proto_rawDescGZIP() []byte {
	file_handle_create_short_url_response_proto_rawDescOnce.Do(func() {
		file_handle_create_short_url_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_handle_create_short_url_response_proto_rawDescData)
	})
	return file_handle_create_short_url_response_proto_rawDescData
}

var file_handle_create_short_url_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_handle_create_short_url_response_proto_goTypes = []any{
	(*HandleCreateShortURLResponse)(nil), // 0: HandleCreateShortURLResponse
	(*Result)(nil),                       // 1: Result
	(*JWT)(nil),                          // 2: JWT
	(*wrapperspb.StringValue)(nil),       // 3: google.protobuf.StringValue
}
var file_handle_create_short_url_response_proto_depIdxs = []int32{
	1, // 0: HandleCreateShortURLResponse.result:type_name -> Result
	2, // 1: HandleCreateShortURLResponse.jwt:type_name -> JWT
	3, // 2: Result.result:type_name -> google.protobuf.StringValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_handle_create_short_url_response_proto_init() }
func file_handle_create_short_url_response_proto_init() {
	if File_handle_create_short_url_response_proto != nil {
		return
	}
	file_wraps_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_handle_create_short_url_response_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HandleCreateShortURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_handle_create_short_url_response_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_handle_create_short_url_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_handle_create_short_url_response_proto_goTypes,
		DependencyIndexes: file_handle_create_short_url_response_proto_depIdxs,
		MessageInfos:      file_handle_create_short_url_response_proto_msgTypes,
	}.Build()
	File_handle_create_short_url_response_proto = out.File
	file_handle_create_short_url_response_proto_rawDesc = nil
	file_handle_create_short_url_response_proto_goTypes = nil
	file_handle_create_short_url_response_proto_depIdxs = nil
}
