# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: http://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
  -   repo: http://github.com/golangci/golangci-lint
      rev: v1.57.2
      hooks:
        -   id: golangci-lint-full
            args: [--config, .golangci.yml]
